imports:
    - php
tools:
  external_code_coverage:
          timeout: 600
checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths:
        - module/Application/src/*
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
