language: php

php:
  - 5.5
  - 5.6

env:
  - BONSAI_URL='127.0.0.1'

services:
  - elasticsearch

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f .travis/vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - php composer.phar install --dev --no-interaction

script:
  - vendor/bin/codecept run --env travis

after_failure:
  - "cat tests/_output/*"
  - "cat module/Application/tests/_output/*"
  - "cat data/logs/app.log"
