language: php

php:
  - 5.5

services:
  - elasticsearch

install:
  - php composer.phar install --dev --no-interaction

before_script:
  - ES_URL=http://127.0.0.1 php -d variables_order=EGPCS -S 0.0.0.0:8000 -t public/ &
  - ES_URL=http://127.0.0.1 php public/index.php load data demo

script:
  - vendor/bin/codecept run --env travis

after_failure:
  - "cat tests/_output/*"
  - "cat module/Application/tests/_output/*"
  - "cat data/logs/app.log"
