language: php

php:
  - 5.5
  - 5.6

env:
  - BONSAI_URL='127.0.0.1'

services:
  - elasticsearch

before_script:
  - php composer.phar install --dev --no-interaction

script:
  - vendor/bin/codecept run
