<div class="row">
    <div class="col-md-12">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('index')); ?>
            <?php echo $this->formText($form->get('index')); ?>
            <?php echo $this->formElementErrors($form->get('index'), array('class' => 'text-danger')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('query')); ?>
            <?php echo $this->formTextarea($form->get('query')); ?>
            <?php echo $this->formElementErrors($form->get('query'), array('class' => 'text-danger')); ?>
        </div>
        <a id="resetbutton" href="/" class="btn btn-danger">Reset</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12">
    <?php
    if (!empty($this->searchEntity->getResult())) {
        echo '<h4>Response</h4>';
        echo '<pre>' . print_r($this->searchEntity->getResult(), true) . '</pre>';
    }
    ?>
    </div>
</div>
